export const LOCATIONS = Object.freeze({
  EXHIBITION: "EXHIBITION",
  ROOM_1: "ROOM_1",
  ROOM_2: "ROOM_2",
  STAIRS: "STAIRS",
  HALLWAY: "HALLWAY",
  SPEAKER_ROOM: "SPEAKER_ROOM",
  TOILET_1: "TOILET_1",
  TOILET_2: "TOILET_2",
  ROOM_3: "ROOM_3",
  ROOM_4: "ROOM_4",
  ENTRANCE: "ENTRANCE",
  EXIT: "EXIT",
});

export type Room = keyof typeof LOCATIONS;

export const MAP: Record<Room, Array<Room>> = {
  [LOCATIONS.EXHIBITION]: [LOCATIONS.ROOM_1],
  [LOCATIONS.ROOM_1]: [LOCATIONS.EXHIBITION, LOCATIONS.ROOM_2, LOCATIONS.ENTRANCE],
  [LOCATIONS.ROOM_2]: [
    LOCATIONS.ROOM_1,
    LOCATIONS.EXIT,
    LOCATIONS.SPEAKER_ROOM,
    LOCATIONS.HALLWAY,
    LOCATIONS.STAIRS,
  ],
  [LOCATIONS.ROOM_3]: [LOCATIONS.STAIRS, LOCATIONS.ROOM_4],
  [LOCATIONS.ROOM_4]: [LOCATIONS.ROOM_4],
  [LOCATIONS.STAIRS]: [LOCATIONS.ROOM_3, LOCATIONS.HALLWAY, LOCATIONS.ROOM_2],
  [LOCATIONS.HALLWAY]: [
    LOCATIONS.ROOM_2,
    LOCATIONS.STAIRS,
    LOCATIONS.SPEAKER_ROOM,
    LOCATIONS.TOILET_1,
    LOCATIONS.TOILET_2,
  ],
  [LOCATIONS.SPEAKER_ROOM]: [LOCATIONS.HALLWAY, LOCATIONS.ROOM_2],
  [LOCATIONS.TOILET_1]: [LOCATIONS.HALLWAY],
  [LOCATIONS.TOILET_2]: [LOCATIONS.HALLWAY],
  [LOCATIONS.ENTRANCE]: [LOCATIONS.ROOM_1],
  [LOCATIONS.EXIT]: [LOCATIONS.ROOM_2],
};
