export const LOCATIONS = Object.freeze({
  EXHIBITION: "EXHIBITION",
  ROOM_1: "ROOM_1",
  ROOM_2: "ROOM_2",
  STAIRS: "STAIRS",
  HALLWAY: "HALLWAY",
  SPEAKER_ROOM: "SPEAKER_ROOM",
  TOILET_1: "TOILET_1",
  TOILET_2: "TOILET_2",
  ROOM_3: "ROOM_3",
  ROOM_4: "ROOM_4",
  ENTRANCE: "ENTRANCE",
  EXIT: "EXIT",
  FIRST_FLOOR: "FIRST_FLOOR",
  SECOND_FLOOR: "SECOND_FLOOR",
});

export type Room = keyof typeof LOCATIONS;

export const MAP: Partial<Record<Room, Array<Room>>> = {
  [LOCATIONS.EXHIBITION]: [LOCATIONS.ROOM_1],
  [LOCATIONS.ROOM_1]: [LOCATIONS.EXHIBITION, LOCATIONS.ROOM_2, LOCATIONS.ENTRANCE],
  [LOCATIONS.ROOM_2]: [
    LOCATIONS.ROOM_1,
    LOCATIONS.EXIT,
    LOCATIONS.SPEAKER_ROOM,
    LOCATIONS.HALLWAY,
    LOCATIONS.STAIRS,
  ],
  [LOCATIONS.ROOM_3]: [LOCATIONS.STAIRS, LOCATIONS.ROOM_4],
  [LOCATIONS.ROOM_4]: [LOCATIONS.ROOM_3],
  [LOCATIONS.STAIRS]: [LOCATIONS.ROOM_3, LOCATIONS.HALLWAY, LOCATIONS.ROOM_2],
  [LOCATIONS.HALLWAY]: [
    LOCATIONS.ROOM_2,
    LOCATIONS.STAIRS,
    LOCATIONS.SPEAKER_ROOM,
    LOCATIONS.TOILET_1,
    LOCATIONS.TOILET_2,
  ],
  [LOCATIONS.SPEAKER_ROOM]: [LOCATIONS.HALLWAY, LOCATIONS.ROOM_2],
  [LOCATIONS.TOILET_1]: [LOCATIONS.HALLWAY],
  [LOCATIONS.TOILET_2]: [LOCATIONS.HALLWAY],
  [LOCATIONS.ENTRANCE]: [LOCATIONS.ROOM_1],
  [LOCATIONS.EXIT]: [LOCATIONS.ROOM_2],
};

export const LOCATION_TO_STRING_MAP = {
  [LOCATIONS.EXHIBITION]: "Exhibition Area",
  [LOCATIONS.ROOM_1]: "Room 1",
  [LOCATIONS.ROOM_2]: "Room 2",
  [LOCATIONS.STAIRS]: "Stairs",
  [LOCATIONS.HALLWAY]: "Hallway",
  [LOCATIONS.SPEAKER_ROOM]: "Speaker Room",
  [LOCATIONS.TOILET_1]: "Toilet",
  [LOCATIONS.TOILET_2]: "Toilet",
  [LOCATIONS.ROOM_3]: "Room 3",
  [LOCATIONS.ROOM_4]: "Room 4",
  [LOCATIONS.ENTRANCE]: "Entrance",
  [LOCATIONS.EXIT]: "Exit",
};

export const STRING_TO_LOCATION_MAP = {
  "Exhibition Area": LOCATIONS.EXHIBITION,
  "Room 1": LOCATIONS.ROOM_1,
  "Room 2": LOCATIONS.ROOM_2,
  Stairs: LOCATIONS.STAIRS,
  Hallway: LOCATIONS.HALLWAY,
  "Speaker Room": LOCATIONS.SPEAKER_ROOM,
  Toilet: LOCATIONS.TOILET_1,
  "Room 3": LOCATIONS.ROOM_3,
  "Room 4": LOCATIONS.ROOM_4,
  Entrance: LOCATIONS.ENTRANCE,
  Exit: LOCATIONS.EXIT,
};
